import { describe, expect, it } from "vitest";
import { customPlaylists, inferTrackMetadata, normalizePlaylists, playlistsToText } from "./metadata.js";

describe("metadata inference", () => {
  it("splits common Artist - Title YouTube titles and creates artist playlists", () => {
    const meta = inferTrackMetadata({
      title: "Cigarettes After Sex - Apocalypse (Official Audio)",
      uploader: "Cigarettes After Sex",
      upload_date: "20170321",
    });

    expect(meta.artist).toBe("Cigarettes After Sex");
    expect(meta.title).toBe("Apocalypse");
    expect(meta.year).toBe("2017");
    expect(meta.album).toBe("2017 - Singles");
    expect(meta.playlists).toEqual([]);
  });

  it("uses the uploader to split Title - Artist YouTube Music titles", () => {
    const meta = inferTrackMetadata({
      title: "Cry - Cigarettes After Sex",
      uploader: "Cigarettes After Sex",
      upload_date: "20191025",
    });

    expect(meta.artist).toBe("Cigarettes After Sex");
    expect(meta.title).toBe("Cry");
    expect(meta.year).toBe("2019");
    expect(meta.album).toBe("2019 - Singles");
    expect(meta.playlists).toEqual([]);
  });

  it("fixes swapped YouTube Music fields using the uploader/title pattern", () => {
    const meta = inferTrackMetadata({
      title: "Cry - Cigarettes After Sex",
      track: "Cigarettes After Sex",
      artist: "Cry",
      uploader: "Cigarettes After Sex",
      upload_date: "20191025",
    });

    expect(meta.artist).toBe("Cigarettes After Sex");
    expect(meta.title).toBe("Cry");
  });

  it("prefers YouTube Music fields over messy YouTube titles", () => {
    const meta = inferTrackMetadata({
      title: "Messy YouTube title (Official Video)",
      track: "Clean Song",
      artist: "Clean Artist",
      album: "Clean Album",
      release_date: "20200630",
    });

    expect(meta.title).toBe("Clean Song");
    expect(meta.artist).toBe("Clean Artist");
    expect(meta.albumArtist).toBe("Clean Artist");
    expect(meta.album).toBe("Clean Album");
    expect(meta.year).toBe("2020");
  });

  it("parses YouTube auto-generated Topic descriptions", () => {
    const meta = inferTrackMetadata({
      title: "Blue Hour",
      uploader: "The Imaginary Band - Topic",
      description: [
        "Provided to YouTube by Some Distributor",
        "",
        "Blue Hour \u00b7 The Imaginary Band",
        "",
        "Night Windows",
        "",
        "\u2117 2021 Some Label",
        "",
        "Released on: 2021-04-09",
        "",
        "Auto-generated by YouTube.",
      ].join("\n"),
    });

    expect(meta.title).toBe("Blue Hour");
    expect(meta.artist).toBe("The Imaginary Band");
    expect(meta.album).toBe("Night Windows");
    expect(meta.year).toBe("2021");
  });

  it("preserves manually supplied albums over inferred albums", () => {
    const meta = inferTrackMetadata({
      title: "Song",
      artist: "Artist",
      album: "YouTube Album",
      release_year: 2024,
    }, {
      album: "My Custom Album",
    });

    expect(meta.album).toBe("My Custom Album");
  });

  it("uses safe defaults when metadata is missing", () => {
    expect(() => inferTrackMetadata({})).not.toThrow();

    const meta = inferTrackMetadata({});
    expect(meta.title).toBe("Untitled");
    expect(meta.artist).toBe("Unknown Artist");
    expect(meta.album).toBe("Singles");
    expect(meta.year).toBe("");
    expect(meta.playlists).toEqual([]);
  });

  it("keeps ambiguous dash titles as Artist - Title without a known artist", () => {
    const meta = inferTrackMetadata({
      title: "Left - Right",
    });

    expect(meta.artist).toBe("Left");
    expect(meta.title).toBe("Right");
  });

  it("normalizes manually typed playlist names", () => {
    expect(normalizePlaylists("iPod - Chill, iPod - Night\n iPod - Chill")).toEqual(["iPod - Chill", "iPod - Night"]);
    expect(playlistsToText(["iPod - A", "iPod - B"])).toBe("iPod - A, iPod - B");
  });

  it("filters generated playlist names and source comments from custom playlists", () => {
    expect(customPlaylists([
      "Chill",
      "iPod - Artist",
      "source:youtube; best available from youtube",
      "This cannot restore YouTube compression.",
    ])).toEqual(["Chill"]);
  });
});
