const INFO_WORDS = [
  "official video",
  "official music video",
  "official audio",
  "official lyric video",
  "lyric video",
  "lyrics",
  "audio",
  "visualizer",
  "music video",
  "hd",
  "4k",
];

function cleanChannelName(value) {
  return String(value || "")
    .replace(/\s*-\s*topic$/i, "")
    .replace(/\s*vevo$/i, "")
    .replace(/\s+official$/i, "")
    .replace(/\s+/g, " ")
    .trim();
}

function cleanText(value) {
  let text = String(value || "")
    .replace(/[“”]/g, "\"")
    .replace(/[‘’]/g, "'")
    .replace(/\s+/g, " ")
    .trim();

  INFO_WORDS.forEach((word) => {
    const escaped = word.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    text = text
      .replace(new RegExp(`\\s*[([{]\\s*${escaped}\\s*[)\\]}]`, "ig"), "")
      .replace(new RegExp(`\\s+-\\s+${escaped}$`, "ig"), "")
      .replace(new RegExp(`\\s+${escaped}$`, "ig"), "");
  });

  return text
    .replace(/\s+\|\s+.*/g, "")
    .replace(/\s+/g, " ")
    .replace(/^["']|["']$/g, "")
    .trim();
}

function sameText(a, b) {
  return cleanText(a).toLowerCase() === cleanText(b).toLowerCase();
}

function usableText(value) {
  const text = cleanText(value);
  return text && !/^(na|n\/a|null|undefined)$/i.test(text) ? text : "";
}

function firstUsable(...values) {
  for (const value of values) {
    const text = usableText(value);
    if (text) return text;
  }
  return "";
}

function firstKnownArtist(...values) {
  for (const value of values) {
    const text = cleanChannelName(firstUsable(value));
    if (text && !sameText(text, "Unknown Artist")) return text;
  }
  return "";
}

function parseYtYear(value) {
  const text = String(value ?? "").trim();
  if (!text) return "";

  const dashed = text.match(/^(\d{4})-\d{2}-\d{2}$/);
  if (dashed) return dashed[1];

  const compact = text.match(/^(\d{4})\d{4}$/);
  if (compact) return compact[1];

  const year = text.match(/^(\d{4})$/);
  return year ? year[1] : "";
}

function isDescriptionMetadataLine(line) {
  return /^released on:/i.test(line)
    || /^auto-generated by youtube\.$/i.test(line)
    || /^provided to youtube by/i.test(line)
    || /^[\u2117\u00a9]/.test(line);
}

function parseAutoGeneratedDescription(description) {
  const result = { title: "", artist: "", album: "", year: "", publisher: "" };

  try {
    const text = String(description || "");
    if (!text.includes("Auto-generated by YouTube.")) return result;

    const lines = text
      .split(/\n\s*\n/)
      .flatMap((block) => block.split(/\n+/))
      .map((line) => line.trim())
      .filter(Boolean);

    const titleArtistIndex = lines.findIndex((line) => line.includes(" \u00b7 "));
    if (titleArtistIndex >= 0) {
      const [titleRaw, ...artistParts] = lines[titleArtistIndex].split(" \u00b7 ");
      result.title = cleanText(titleRaw);
      result.artist = cleanChannelName(artistParts.join(" \u00b7 "));

      for (let i = titleArtistIndex + 1; i < lines.length; i += 1) {
        if (!isDescriptionMetadataLine(lines[i])) {
          result.album = cleanText(lines[i]);
          break;
        }
      }
    }

    const releaseLine = lines.find((line) => /^released on:/i.test(line));
    result.year = parseYtYear(releaseLine?.replace(/^released on:\s*/i, ""));

    const publisherLine = lines.find((line) => /^[\u2117]/.test(line));
    result.publisher = cleanText(publisherLine?.replace(/^[\u2117]\s*/, ""));
  } catch {
    return { title: "", artist: "", album: "", year: "", publisher: "" };
  }

  return result;
}

function bestKnownArtist(info = {}, fallback = {}) {
  return firstKnownArtist(
    info.artist,
    info.creator,
    info.uploader,
    info.channel,
    fallback.artist,
  );
}

function channelKnownArtist(info = {}, fallback = {}) {
  return firstKnownArtist(
    info.uploader,
    info.channel,
    info.creator,
    fallback.artist,
  );
}

function splitArtistTitle(title, knownArtist = "") {
  const separators = [" - ", " – ", " — ", " -- "];
  for (const sep of separators) {
    if (title.includes(sep)) {
      const [leftRaw, ...rest] = title.split(sep);
      const rightRaw = rest.join(sep);
      const left = cleanText(leftRaw);
      const right = cleanText(rightRaw);
      if (!left || !right) continue;
      if (knownArtist && sameText(right, knownArtist)) return { artist: right, title: left };
      if (knownArtist && sameText(left, knownArtist)) return { artist: left, title: right };
      return { artist: left, title: right };
    }
  }
  return null;
}

function uniq(values) {
  return [...new Set(values.map((value) => String(value || "").trim()).filter(Boolean))];
}

export function normalizePlaylists(value) {
  if (Array.isArray(value)) return uniq(value);
  return uniq(String(value || "").split(/[,\n]+/));
}

export function isAutoPlaylistName(value) {
  return /^ipod\s*-/i.test(String(value || "").trim());
}

export function customPlaylists(value) {
  return normalizePlaylists(value).filter((name) => !isAutoPlaylistName(name));
}

export function playlistsToText(playlists) {
  return normalizePlaylists(playlists).join(", ");
}

export function inferTrackMetadata(info = {}, fallback = {}) {
  const rawTitle = cleanText(info.title || "");
  const description = parseAutoGeneratedDescription(info.description);
  const channelArtist = channelKnownArtist(info, fallback);
  const knownArtist = bestKnownArtist(info, fallback);
  const split = splitArtistTitle(rawTitle, channelArtist) || splitArtistTitle(rawTitle, knownArtist);
  const title = firstUsable(description.title, split?.title, info.track, info.alt_title, rawTitle, fallback.title, "Untitled");
  const artist = firstKnownArtist(description.artist, split?.artist, info.artist, knownArtist) || "Unknown Artist";
  const year = firstUsable(
    parseYtYear(info.release_year),
    parseYtYear(info.release_date),
    description.year,
    parseYtYear(info.upload_date),
    parseYtYear(fallback.year),
  );
  const fallbackAlbum = firstUsable(fallback.album);
  const inferredAlbum = firstUsable(info.album, description.album);
  const album = fallbackAlbum && !sameText(fallbackAlbum, "Unknown Album") && !sameText(fallbackAlbum, "YouTube imports")
    ? fallbackAlbum
    : inferredAlbum || (year ? `${year} - Singles` : "Singles");

  const playlists = customPlaylists(fallback.playlists || []);

  return {
    title,
    artist,
    album,
    albumArtist: artist,
    year,
    playlists,
    comment: fallback.comment || "Source=YouTube; best available from YouTube. This cannot restore YouTube compression.",
  };
}
